


#Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);

#Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS 'Average Product Rating'
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type, ROUND(AVG(purchase_amount), 2) as avg_purchase
FROM
    customer
WHERE
    shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue 
#between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend DESC;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied
SELECT 
    item_purchased,
    ROUND((COUNT(item_purchased) / (SELECT 
                    COUNT(*)
                FROM
                    customer)) * 100,
            2) AS pop
FROM
    customer
WHERE
    discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY pop DESC
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with my_cte as (select *,
case 
when previous_purchases=1 then 'New'
when previous_purchases>10 then  'Loyal'
else 'Returning' end as Customer_Segments
from customer)


select  Customer_Segments , count(Customer_Segments) as number_of_customer
from my_cte 
group by Customer_Segments;

#Q8. What are the top 3 most purchased products within each category?
with my_cte as (select category , item_purchased , count(item_purchased)  as cnt 
from customer 
group by category , item_purchased
order by category),

my_cte2 as(SELECT
    category,
    item_purchased,
    cnt,
    ROW_NUMBER() OVER (
        PARTITION BY category
        ORDER BY cnt desc
    ) AS rn
FROM my_cte)

select category , item_purchased
from my_cte2
where rn<=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group?
SELECT 
    age_group, SUM(purchase_amount) AS revenue
FROM
    customer
GROUP BY age_group
ORDER BY revenue DESC;












